include:
  - https://cnb.cool/seer-robotics/IT/plugins-sbs360-lpm/-/blob/main/.cnb.yml

$:
  pull_request.target:
    - stages:
        - name: 添加评审人
          type: git:reviewer
          options:
            type: add-reviewer
            reviewers: chenhongli
            exclude: ${CNB_BUILD_USER}

        - name: AI 评审
          allowFailure: true  # 失败不影响流水线状态
          image: cnbcool/code-review:latest
          settings:
            comment: true
            max_comments: 10
            fail_on_critical: true
