# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_script.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='message_script.proto',
    package='rbk.protocol',
    syntax='proto3',
    serialized_options=None,
    serialized_pb=_b(
        '\n\x14message_script.proto\x12\x0crbk.protocol\"\xd8\x01\n\x14Message_ScriptStatus\x12\x39\n\x06status\x18\x01 \x01(\x0e\x32).rbk.protocol.Message_ScriptStatus.Status\x12\x0b\n\x03res\x18\x02 \x01(\t\"x\n\x06Status\x12\x0e\n\nStatusNone\x10\x00\x12\x0b\n\x07Waiting\x10\x01\x12\x0b\n\x07Running\x10\x02\x12\r\n\tSuspended\x10\x03\x12\r\n\tCompleted\x10\x04\x12\n\n\x06\x46\x61iled\x10\x05\x12\x0c\n\x08\x43\x61nceled\x10\x06\x12\x0c\n\x08OverTime\x10\x07\"\x86\x01\n\x0eMessage_Script\x12\x41\n\x0bscript_data\x18\x01 \x03(\x0b\x32,.rbk.protocol.Message_Script.ScriptDataEntry\x1a\x31\n\x0fScriptDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')
)

_MESSAGE_SCRIPTSTATUS_STATUS = _descriptor.EnumDescriptor(
    name='Status',
    full_name='rbk.protocol.Message_ScriptStatus.Status',
    filename=None,
    file=DESCRIPTOR,
    values=[
        _descriptor.EnumValueDescriptor(
            name='StatusNone', index=0, number=0,
            serialized_options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='Waiting', index=1, number=1,
            serialized_options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='Running', index=2, number=2,
            serialized_options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='Suspended', index=3, number=3,
            serialized_options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='Completed', index=4, number=4,
            serialized_options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='Failed', index=5, number=5,
            serialized_options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='Canceled', index=6, number=6,
            serialized_options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='OverTime', index=7, number=7,
            serialized_options=None,
            type=None),
    ],
    containing_type=None,
    serialized_options=None,
    serialized_start=135,
    serialized_end=255,
)
_sym_db.RegisterEnumDescriptor(_MESSAGE_SCRIPTSTATUS_STATUS)

_MESSAGE_SCRIPTSTATUS = _descriptor.Descriptor(
    name='Message_ScriptStatus',
    full_name='rbk.protocol.Message_ScriptStatus',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='status', full_name='rbk.protocol.Message_ScriptStatus.status', index=0,
            number=1, type=14, cpp_type=8, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='res', full_name='rbk.protocol.Message_ScriptStatus.res', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
        _MESSAGE_SCRIPTSTATUS_STATUS,
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=39,
    serialized_end=255,
)

_MESSAGE_SCRIPT_SCRIPTDATAENTRY = _descriptor.Descriptor(
    name='ScriptDataEntry',
    full_name='rbk.protocol.Message_Script.ScriptDataEntry',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='key', full_name='rbk.protocol.Message_Script.ScriptDataEntry.key', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='value', full_name='rbk.protocol.Message_Script.ScriptDataEntry.value', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=_b('8\001'),
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=343,
    serialized_end=392,
)

_MESSAGE_SCRIPT = _descriptor.Descriptor(
    name='Message_Script',
    full_name='rbk.protocol.Message_Script',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='script_data', full_name='rbk.protocol.Message_Script.script_data', index=0,
            number=1, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[_MESSAGE_SCRIPT_SCRIPTDATAENTRY, ],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=258,
    serialized_end=392,
)

_MESSAGE_SCRIPTSTATUS.fields_by_name['status'].enum_type = _MESSAGE_SCRIPTSTATUS_STATUS
_MESSAGE_SCRIPTSTATUS_STATUS.containing_type = _MESSAGE_SCRIPTSTATUS
_MESSAGE_SCRIPT_SCRIPTDATAENTRY.containing_type = _MESSAGE_SCRIPT
_MESSAGE_SCRIPT.fields_by_name['script_data'].message_type = _MESSAGE_SCRIPT_SCRIPTDATAENTRY
DESCRIPTOR.message_types_by_name['Message_ScriptStatus'] = _MESSAGE_SCRIPTSTATUS
DESCRIPTOR.message_types_by_name['Message_Script'] = _MESSAGE_SCRIPT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Message_ScriptStatus = _reflection.GeneratedProtocolMessageType('Message_ScriptStatus', (_message.Message,), dict(
    DESCRIPTOR=_MESSAGE_SCRIPTSTATUS,
    __module__='message_script_pb2'
    # @@protoc_insertion_point(class_scope:rbk.protocol.Message_ScriptStatus)
))
_sym_db.RegisterMessage(Message_ScriptStatus)

Message_Script = _reflection.GeneratedProtocolMessageType('Message_Script', (_message.Message,), dict(

    ScriptDataEntry=_reflection.GeneratedProtocolMessageType('ScriptDataEntry', (_message.Message,), dict(
        DESCRIPTOR=_MESSAGE_SCRIPT_SCRIPTDATAENTRY,
        __module__='message_script_pb2'
        # @@protoc_insertion_point(class_scope:rbk.protocol.Message_Script.ScriptDataEntry)
    ))
    ,
    DESCRIPTOR=_MESSAGE_SCRIPT,
    __module__='message_script_pb2'
    # @@protoc_insertion_point(class_scope:rbk.protocol.Message_Script)
))
_sym_db.RegisterMessage(Message_Script)
_sym_db.RegisterMessage(Message_Script.ScriptDataEntry)

_MESSAGE_SCRIPT_SCRIPTDATAENTRY._options = None
# @@protoc_insertion_point(module_scope)
