# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CanFrame.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='CanFrame.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0e\x43\x61nFrame.proto\"\xad\x01\n\x08\x43\x61nFrame\x12\n\n\x02id\x18\x01 \x01(\r\x12\x10\n\x08\x65xtended\x18\x02 \x01(\x08\x12\x0e\n\x06remote\x18\x03 \x01(\x08\x12\x0b\n\x03\x64lc\x18\x04 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x05 \x01(\x0c\x12\x0f\n\x07\x63hannel\x18\x06 \x01(\r\x12\x11\n\ttimestamp\x18\x07 \x01(\r\x12\x11\n\tdirection\x18\x08 \x01(\x08\x12!\n\x08\x63\x61nError\x18\t \x03(\x0b\x32\x0f.CanErrorRecord\"7\n\x0e\x43\x61nErrorRecord\x12\x11\n\terrortype\x18\x01 \x01(\r\x12\x12\n\nerrorcount\x18\x02 \x01(\r*\x1b\n\tDIRE_ENUM\x12\x06\n\x02RX\x10\x00\x12\x06\n\x02TX\x10\x01*\x88\x01\n\nERROR_TYPE\x12\x0f\n\x0bSTUFF_ERROR\x10\x00\x12\x0e\n\nFORM_ERROR\x10\x01\x12\x19\n\x15\x41\x43KNOWLEDGEMENT_ERROR\x10\x02\x12\x17\n\x13\x42IT_RECESSIVE_ERROR\x10\x03\x12\x16\n\x12\x42IT_DOMINANT_ERROR\x10\x04\x12\r\n\tCRC_ERROR\x10\x05\x62\x06proto3')
)

_DIRE_ENUM = _descriptor.EnumDescriptor(
  name='DIRE_ENUM',
  full_name='DIRE_ENUM',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RX', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TX', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=251,
  serialized_end=278,
)
_sym_db.RegisterEnumDescriptor(_DIRE_ENUM)

DIRE_ENUM = enum_type_wrapper.EnumTypeWrapper(_DIRE_ENUM)
_ERROR_TYPE = _descriptor.EnumDescriptor(
  name='ERROR_TYPE',
  full_name='ERROR_TYPE',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STUFF_ERROR', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FORM_ERROR', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACKNOWLEDGEMENT_ERROR', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BIT_RECESSIVE_ERROR', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BIT_DOMINANT_ERROR', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CRC_ERROR', index=5, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=281,
  serialized_end=417,
)
_sym_db.RegisterEnumDescriptor(_ERROR_TYPE)

ERROR_TYPE = enum_type_wrapper.EnumTypeWrapper(_ERROR_TYPE)
RX = 0
TX = 1
STUFF_ERROR = 0
FORM_ERROR = 1
ACKNOWLEDGEMENT_ERROR = 2
BIT_RECESSIVE_ERROR = 3
BIT_DOMINANT_ERROR = 4
CRC_ERROR = 5



_CANFRAME = _descriptor.Descriptor(
  name='CanFrame',
  full_name='CanFrame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='CanFrame.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='extended', full_name='CanFrame.extended', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='remote', full_name='CanFrame.remote', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dlc', full_name='CanFrame.dlc', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='CanFrame.data', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='channel', full_name='CanFrame.channel', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='CanFrame.timestamp', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='direction', full_name='CanFrame.direction', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='canError', full_name='CanFrame.canError', index=8,
      number=9, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=192,
)


_CANERRORRECORD = _descriptor.Descriptor(
  name='CanErrorRecord',
  full_name='CanErrorRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='errortype', full_name='CanErrorRecord.errortype', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='errorcount', full_name='CanErrorRecord.errorcount', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=194,
  serialized_end=249,
)

_CANFRAME.fields_by_name['canError'].message_type = _CANERRORRECORD
DESCRIPTOR.message_types_by_name['CanFrame'] = _CANFRAME
DESCRIPTOR.message_types_by_name['CanErrorRecord'] = _CANERRORRECORD
DESCRIPTOR.enum_types_by_name['DIRE_ENUM'] = _DIRE_ENUM
DESCRIPTOR.enum_types_by_name['ERROR_TYPE'] = _ERROR_TYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CanFrame = _reflection.GeneratedProtocolMessageType('CanFrame', (_message.Message,), dict(
  DESCRIPTOR = _CANFRAME,
  __module__ = 'CanFrame_pb2'
  # @@protoc_insertion_point(class_scope:CanFrame)
  ))
_sym_db.RegisterMessage(CanFrame)

CanErrorRecord = _reflection.GeneratedProtocolMessageType('CanErrorRecord', (_message.Message,), dict(
  DESCRIPTOR = _CANERRORRECORD,
  __module__ = 'CanFrame_pb2'
  # @@protoc_insertion_point(class_scope:CanErrorRecord)
  ))
_sym_db.RegisterMessage(CanErrorRecord)


# @@protoc_insertion_point(module_scope)
