# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_devicestatus.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import message_header_pb2 as message__header__pb2
from . import message_error_pb2 as message__error__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='message_devicestatus.proto',
  package='rbk.protocol',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1amessage_devicestatus.proto\x12\x0crbk.protocol\x1a\x14message_header.proto\x1a\x13message_error.proto\"\xec\x02\n\x13msgDeviceStatusNode\x12\'\n\x06header\x18\x01 \x01(\x0b\x32\x17.rbk.protocol.msgHeader\x12H\n\x0estatusCategory\x18\x02 \x01(\x0e\x32\x30.rbk.protocol.msgDeviceStatusNode.StatusCategory\x12=\n\x06\x65rrors\x18\x03 \x03(\x0b\x32-.rbk.protocol.msgDeviceStatusNode.ErrorsEntry\x1a\x45\n\x0b\x45rrorsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12%\n\x05value\x18\x02 \x01(\x0b\x32\x16.rbk.protocol.msgError:\x02\x38\x01\"\\\n\x0eStatusCategory\x12\x08\n\x04INIT\x10\x00\x12\x0b\n\x07RUNNING\x10\x01\x12\x11\n\rCONNECT_ERROR\x10\x02\x12\x0e\n\nDATA_ERROR\x10\x03\x12\x10\n\x0c\x44\x45VICE_ERROR\x10\x04\"\xd9\x01\n\x0fmsgDeviceStatus\x12\'\n\x06header\x18\x01 \x01(\x0b\x32\x17.rbk.protocol.msgHeader\x12\x45\n\x0c\x64\x65viceStatus\x18\x02 \x03(\x0b\x32/.rbk.protocol.msgDeviceStatus.DeviceStatusEntry\x1aV\n\x11\x44\x65viceStatusEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x30\n\x05value\x18\x02 \x01(\x0b\x32!.rbk.protocol.msgDeviceStatusNode:\x02\x38\x01\x62\x06proto3')
  ,
  dependencies=[message__header__pb2.DESCRIPTOR,message__error__pb2.DESCRIPTOR,])



_MSGDEVICESTATUSNODE_STATUSCATEGORY = _descriptor.EnumDescriptor(
  name='StatusCategory',
  full_name='rbk.protocol.msgDeviceStatusNode.StatusCategory',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INIT', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RUNNING', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONNECT_ERROR', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DATA_ERROR', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DEVICE_ERROR', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=360,
  serialized_end=452,
)
_sym_db.RegisterEnumDescriptor(_MSGDEVICESTATUSNODE_STATUSCATEGORY)


_MSGDEVICESTATUSNODE_ERRORSENTRY = _descriptor.Descriptor(
  name='ErrorsEntry',
  full_name='rbk.protocol.msgDeviceStatusNode.ErrorsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='rbk.protocol.msgDeviceStatusNode.ErrorsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='rbk.protocol.msgDeviceStatusNode.ErrorsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=289,
  serialized_end=358,
)

_MSGDEVICESTATUSNODE = _descriptor.Descriptor(
  name='msgDeviceStatusNode',
  full_name='rbk.protocol.msgDeviceStatusNode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='rbk.protocol.msgDeviceStatusNode.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='statusCategory', full_name='rbk.protocol.msgDeviceStatusNode.statusCategory', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='errors', full_name='rbk.protocol.msgDeviceStatusNode.errors', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_MSGDEVICESTATUSNODE_ERRORSENTRY, ],
  enum_types=[
    _MSGDEVICESTATUSNODE_STATUSCATEGORY,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=452,
)


_MSGDEVICESTATUS_DEVICESTATUSENTRY = _descriptor.Descriptor(
  name='DeviceStatusEntry',
  full_name='rbk.protocol.msgDeviceStatus.DeviceStatusEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='rbk.protocol.msgDeviceStatus.DeviceStatusEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='rbk.protocol.msgDeviceStatus.DeviceStatusEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=586,
  serialized_end=672,
)

_MSGDEVICESTATUS = _descriptor.Descriptor(
  name='msgDeviceStatus',
  full_name='rbk.protocol.msgDeviceStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='rbk.protocol.msgDeviceStatus.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deviceStatus', full_name='rbk.protocol.msgDeviceStatus.deviceStatus', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_MSGDEVICESTATUS_DEVICESTATUSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=455,
  serialized_end=672,
)

_MSGDEVICESTATUSNODE_ERRORSENTRY.fields_by_name['value'].message_type = message__error__pb2._MSGERROR
_MSGDEVICESTATUSNODE_ERRORSENTRY.containing_type = _MSGDEVICESTATUSNODE
_MSGDEVICESTATUSNODE.fields_by_name['header'].message_type = message__header__pb2._MSGHEADER
_MSGDEVICESTATUSNODE.fields_by_name['statusCategory'].enum_type = _MSGDEVICESTATUSNODE_STATUSCATEGORY
_MSGDEVICESTATUSNODE.fields_by_name['errors'].message_type = _MSGDEVICESTATUSNODE_ERRORSENTRY
_MSGDEVICESTATUSNODE_STATUSCATEGORY.containing_type = _MSGDEVICESTATUSNODE
_MSGDEVICESTATUS_DEVICESTATUSENTRY.fields_by_name['value'].message_type = _MSGDEVICESTATUSNODE
_MSGDEVICESTATUS_DEVICESTATUSENTRY.containing_type = _MSGDEVICESTATUS
_MSGDEVICESTATUS.fields_by_name['header'].message_type = message__header__pb2._MSGHEADER
_MSGDEVICESTATUS.fields_by_name['deviceStatus'].message_type = _MSGDEVICESTATUS_DEVICESTATUSENTRY
DESCRIPTOR.message_types_by_name['msgDeviceStatusNode'] = _MSGDEVICESTATUSNODE
DESCRIPTOR.message_types_by_name['msgDeviceStatus'] = _MSGDEVICESTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

msgDeviceStatusNode = _reflection.GeneratedProtocolMessageType('msgDeviceStatusNode', (_message.Message,), dict(

  ErrorsEntry = _reflection.GeneratedProtocolMessageType('ErrorsEntry', (_message.Message,), dict(
    DESCRIPTOR = _MSGDEVICESTATUSNODE_ERRORSENTRY,
    __module__ = 'message_devicestatus_pb2'
    # @@protoc_insertion_point(class_scope:rbk.protocol.msgDeviceStatusNode.ErrorsEntry)
    ))
  ,
  DESCRIPTOR = _MSGDEVICESTATUSNODE,
  __module__ = 'message_devicestatus_pb2'
  # @@protoc_insertion_point(class_scope:rbk.protocol.msgDeviceStatusNode)
  ))
_sym_db.RegisterMessage(msgDeviceStatusNode)
_sym_db.RegisterMessage(msgDeviceStatusNode.ErrorsEntry)

msgDeviceStatus = _reflection.GeneratedProtocolMessageType('msgDeviceStatus', (_message.Message,), dict(

  DeviceStatusEntry = _reflection.GeneratedProtocolMessageType('DeviceStatusEntry', (_message.Message,), dict(
    DESCRIPTOR = _MSGDEVICESTATUS_DEVICESTATUSENTRY,
    __module__ = 'message_devicestatus_pb2'
    # @@protoc_insertion_point(class_scope:rbk.protocol.msgDeviceStatus.DeviceStatusEntry)
    ))
  ,
  DESCRIPTOR = _MSGDEVICESTATUS,
  __module__ = 'message_devicestatus_pb2'
  # @@protoc_insertion_point(class_scope:rbk.protocol.msgDeviceStatus)
  ))
_sym_db.RegisterMessage(msgDeviceStatus)
_sym_db.RegisterMessage(msgDeviceStatus.DeviceStatusEntry)


_MSGDEVICESTATUSNODE_ERRORSENTRY._options = None
_MSGDEVICESTATUS_DEVICESTATUSENTRY._options = None
# @@protoc_insertion_point(module_scope)
