# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_calibstatus.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message_calibstatus.proto',
  package='rbk.protocol',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x19message_calibstatus.proto\x12\x0crbk.protocol\"\x99\x01\n\x0emsgCalibStatus\x12\x38\n\x06status\x18\x07 \x01(\x0e\x32(.rbk.protocol.msgCalibStatus.calibStatus\x12\x0c\n\x04\x64\x65sc\x18\x08 \x01(\t\"?\n\x0b\x63\x61libStatus\x12\x08\n\x04none\x10\x00\x12\x0b\n\x07running\x10\x01\x12\r\n\tcompleted\x10\x02\x12\n\n\x06\x66\x61iled\x10\x03\x62\x06proto3')
)



_MSGCALIBSTATUS_CALIBSTATUS = _descriptor.EnumDescriptor(
  name='calibStatus',
  full_name='rbk.protocol.msgCalibStatus.calibStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='none', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='running', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='completed', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='failed', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=134,
  serialized_end=197,
)
_sym_db.RegisterEnumDescriptor(_MSGCALIBSTATUS_CALIBSTATUS)


_MSGCALIBSTATUS = _descriptor.Descriptor(
  name='msgCalibStatus',
  full_name='rbk.protocol.msgCalibStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='rbk.protocol.msgCalibStatus.status', index=0,
      number=7, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='desc', full_name='rbk.protocol.msgCalibStatus.desc', index=1,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MSGCALIBSTATUS_CALIBSTATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=197,
)

_MSGCALIBSTATUS.fields_by_name['status'].enum_type = _MSGCALIBSTATUS_CALIBSTATUS
_MSGCALIBSTATUS_CALIBSTATUS.containing_type = _MSGCALIBSTATUS
DESCRIPTOR.message_types_by_name['msgCalibStatus'] = _MSGCALIBSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

msgCalibStatus = _reflection.GeneratedProtocolMessageType('msgCalibStatus', (_message.Message,), dict(
  DESCRIPTOR = _MSGCALIBSTATUS,
  __module__ = 'message_calibstatus_pb2'
  # @@protoc_insertion_point(class_scope:rbk.protocol.msgCalibStatus)
  ))
_sym_db.RegisterMessage(msgCalibStatus)


# @@protoc_insertion_point(module_scope)
