# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_distancesensor.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import message_header_pb2 as message__header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='message_distancesensor.proto',
  package='rbk.protocol',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1cmessage_distancesensor.proto\x12\x0crbk.protocol\x1a\x14message_header.proto\"\xf3\x01\n\x0fmsgDistanceNode\x12\'\n\x06header\x18\x01 \x01(\x0b\x32\x17.rbk.protocol.msgHeader\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\x05\x12\x0c\n\x04\x64ist\x18\x04 \x01(\x02\x12\r\n\x05valid\x18\x05 \x01(\x08\x12\x0c\n\x04posX\x18\x06 \x01(\x02\x12\x0c\n\x04posY\x18\x07 \x01(\x02\x12\x10\n\x08posAngle\x18\x08 \x01(\x02\x12\x10\n\x08\x61perture\x18\t \x01(\x02\x12\x11\n\tforbidden\x18\n \x01(\x08\x12\x11\n\tcanRouter\x18\x0b \x01(\r\x12\r\n\x05rs485\x18\x0c \x01(\r\x12\x0c\n\x04RSSI\x18\r \x01(\r\"@\n\x11msgDistanceSensor\x12+\n\x04node\x18\x01 \x03(\x0b\x32\x1d.rbk.protocol.msgDistanceNodeb\x06proto3')
  ,
  dependencies=[message__header__pb2.DESCRIPTOR,])




_MSGDISTANCENODE = _descriptor.Descriptor(
  name='msgDistanceNode',
  full_name='rbk.protocol.msgDistanceNode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='rbk.protocol.msgDistanceNode.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key', full_name='rbk.protocol.msgDistanceNode.key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='rbk.protocol.msgDistanceNode.id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dist', full_name='rbk.protocol.msgDistanceNode.dist', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='valid', full_name='rbk.protocol.msgDistanceNode.valid', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='posX', full_name='rbk.protocol.msgDistanceNode.posX', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='posY', full_name='rbk.protocol.msgDistanceNode.posY', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='posAngle', full_name='rbk.protocol.msgDistanceNode.posAngle', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='aperture', full_name='rbk.protocol.msgDistanceNode.aperture', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='forbidden', full_name='rbk.protocol.msgDistanceNode.forbidden', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='canRouter', full_name='rbk.protocol.msgDistanceNode.canRouter', index=10,
      number=11, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rs485', full_name='rbk.protocol.msgDistanceNode.rs485', index=11,
      number=12, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='RSSI', full_name='rbk.protocol.msgDistanceNode.RSSI', index=12,
      number=13, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=312,
)


_MSGDISTANCESENSOR = _descriptor.Descriptor(
  name='msgDistanceSensor',
  full_name='rbk.protocol.msgDistanceSensor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='node', full_name='rbk.protocol.msgDistanceSensor.node', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=314,
  serialized_end=378,
)

_MSGDISTANCENODE.fields_by_name['header'].message_type = message__header__pb2._MSGHEADER
_MSGDISTANCESENSOR.fields_by_name['node'].message_type = _MSGDISTANCENODE
DESCRIPTOR.message_types_by_name['msgDistanceNode'] = _MSGDISTANCENODE
DESCRIPTOR.message_types_by_name['msgDistanceSensor'] = _MSGDISTANCESENSOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

msgDistanceNode = _reflection.GeneratedProtocolMessageType('msgDistanceNode', (_message.Message,), dict(
  DESCRIPTOR = _MSGDISTANCENODE,
  __module__ = 'message_distancesensor_pb2'
  # @@protoc_insertion_point(class_scope:rbk.protocol.msgDistanceNode)
  ))
_sym_db.RegisterMessage(msgDistanceNode)

msgDistanceSensor = _reflection.GeneratedProtocolMessageType('msgDistanceSensor', (_message.Message,), dict(
  DESCRIPTOR = _MSGDISTANCESENSOR,
  __module__ = 'message_distancesensor_pb2'
  # @@protoc_insertion_point(class_scope:rbk.protocol.msgDistanceSensor)
  ))
_sym_db.RegisterMessage(msgDistanceSensor)


# @@protoc_insertion_point(module_scope)
