# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_depthcamera.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import message_header_pb2 as message__header__pb2
from . import message_recogresult_pb2 as message__recogresult__pb2
from . import message_calibration_pb2 as message__calibration__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='message_depthcamera.proto',
  package='rbk.protocol',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x19message_depthcamera.proto\x12\x0crbk.protocol\x1a\x14message_header.proto\x1a\x19message_recogresult.proto\x1a\x19message_calibration.proto\"\xba\x01\n\x0emsgDataPackage\x12\'\n\x06header\x18\x01 \x01(\x0b\x32\x17.rbk.protocol.msgHeader\x12.\n\tcloudData\x18\x02 \x01(\x0b\x32\x1b.rbk.protocol.msgPointCloud\x12\'\n\x07rgbData\x18\x03 \x01(\x0b\x32\x16.rbk.protocol.msgImage\x12&\n\x06irData\x18\x04 \x01(\x0b\x32\x16.rbk.protocol.msgImageb\x06proto3')
  ,
  dependencies=[message__header__pb2.DESCRIPTOR,message__recogresult__pb2.DESCRIPTOR,message__calibration__pb2.DESCRIPTOR,])




_MSGDATAPACKAGE = _descriptor.Descriptor(
  name='msgDataPackage',
  full_name='rbk.protocol.msgDataPackage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='rbk.protocol.msgDataPackage.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cloudData', full_name='rbk.protocol.msgDataPackage.cloudData', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rgbData', full_name='rbk.protocol.msgDataPackage.rgbData', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='irData', full_name='rbk.protocol.msgDataPackage.irData', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=306,
)

_MSGDATAPACKAGE.fields_by_name['header'].message_type = message__header__pb2._MSGHEADER
_MSGDATAPACKAGE.fields_by_name['cloudData'].message_type = message__recogresult__pb2._MSGPOINTCLOUD
_MSGDATAPACKAGE.fields_by_name['rgbData'].message_type = message__calibration__pb2._MSGIMAGE
_MSGDATAPACKAGE.fields_by_name['irData'].message_type = message__calibration__pb2._MSGIMAGE
DESCRIPTOR.message_types_by_name['msgDataPackage'] = _MSGDATAPACKAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

msgDataPackage = _reflection.GeneratedProtocolMessageType('msgDataPackage', (_message.Message,), dict(
  DESCRIPTOR = _MSGDATAPACKAGE,
  __module__ = 'message_depthcamera_pb2'
  # @@protoc_insertion_point(class_scope:rbk.protocol.msgDataPackage)
  ))
_sym_db.RegisterMessage(msgDataPackage)


# @@protoc_insertion_point(module_scope)
