# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_error.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message_error.proto',
  package='rbk.protocol',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13message_error.proto\x12\x0crbk.protocol\"B\n\x0emsgConfigError\x12\x10\n\x08\x66ileName\x18\x01 \x01(\t\x12\x0f\n\x07\x61ppType\x18\x02 \x01(\t\x12\r\n\x05param\x18\x03 \x01(\t\"k\n\x0emsgDeviceError\x12\x10\n\x08\x66ileName\x18\x01 \x01(\t\x12\x12\n\ndeviceType\x18\x02 \x01(\t\x12\x11\n\tdeviceKey\x18\x03 \x01(\t\x12\r\n\x05param\x18\x04 \x01(\t\x12\x11\n\terrorCode\x18\x05 \x01(\r\"Y\n\x0bmsgMapError\x12\x0f\n\x07mapType\x18\x01 \x01(\t\x12\x0f\n\x07mapName\x18\x02 \x01(\t\x12\x13\n\x0b\x65lementType\x18\x03 \x01(\t\x12\x13\n\x0b\x65lementName\x18\x04 \x01(\t\"&\n\x0fmsgLicenseError\x12\x13\n\x0blicenseType\x18\x01 \x01(\t\"\x1c\n\x0cmsgTaskError\x12\x0c\n\x04task\x18\x01 \x01(\t\"\xb6\x02\n\x08msgError\x12\x33\n\x0b\x64\x65viceError\x18\x01 \x01(\x0b\x32\x1c.rbk.protocol.msgDeviceErrorH\x00\x12\x33\n\x0b\x63onfigError\x18\x02 \x01(\x0b\x32\x1c.rbk.protocol.msgConfigErrorH\x00\x12-\n\x08mapError\x18\x03 \x01(\x0b\x32\x19.rbk.protocol.msgMapErrorH\x00\x12\x35\n\x0clicenseError\x18\x04 \x01(\x0b\x32\x1d.rbk.protocol.msgLicenseErrorH\x00\x12/\n\ttaskError\x18\x05 \x01(\x0b\x32\x1a.rbk.protocol.msgTaskErrorH\x00\x12\x0c\n\x04\x64\x65sc\x18\x06 \x01(\t\x12\x0e\n\x06manual\x18\x07 \x01(\x08\x42\x0b\n\terrorType\"\x92\x02\n\x0fmsgSystemStatus\x12:\n\x06status\x18\x01 \x01(\x0e\x32*.rbk.protocol.msgSystemStatus.systemStatus\x12\x39\n\x06\x65rrors\x18\x02 \x03(\x0b\x32).rbk.protocol.msgSystemStatus.ErrorsEntry\x1a\x45\n\x0b\x45rrorsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12%\n\x05value\x18\x02 \x01(\x0b\x32\x16.rbk.protocol.msgError:\x02\x38\x01\"A\n\x0csystemStatus\x12\x0c\n\x08starting\x10\x00\x12\x0b\n\x07running\x10\x01\x12\t\n\x05\x65rror\x10\x02\x12\x0b\n\x07\x63rashed\x10\x03\x62\x06proto3')
)



_MSGSYSTEMSTATUS_SYSTEMSTATUS = _descriptor.EnumDescriptor(
  name='systemStatus',
  full_name='rbk.protocol.msgSystemStatus.systemStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='starting', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='running', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='error', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='crashed', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=898,
  serialized_end=963,
)
_sym_db.RegisterEnumDescriptor(_MSGSYSTEMSTATUS_SYSTEMSTATUS)


_MSGCONFIGERROR = _descriptor.Descriptor(
  name='msgConfigError',
  full_name='rbk.protocol.msgConfigError',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fileName', full_name='rbk.protocol.msgConfigError.fileName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='appType', full_name='rbk.protocol.msgConfigError.appType', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='param', full_name='rbk.protocol.msgConfigError.param', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=103,
)


_MSGDEVICEERROR = _descriptor.Descriptor(
  name='msgDeviceError',
  full_name='rbk.protocol.msgDeviceError',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fileName', full_name='rbk.protocol.msgDeviceError.fileName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deviceType', full_name='rbk.protocol.msgDeviceError.deviceType', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deviceKey', full_name='rbk.protocol.msgDeviceError.deviceKey', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='param', full_name='rbk.protocol.msgDeviceError.param', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='errorCode', full_name='rbk.protocol.msgDeviceError.errorCode', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=212,
)


_MSGMAPERROR = _descriptor.Descriptor(
  name='msgMapError',
  full_name='rbk.protocol.msgMapError',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mapType', full_name='rbk.protocol.msgMapError.mapType', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mapName', full_name='rbk.protocol.msgMapError.mapName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='elementType', full_name='rbk.protocol.msgMapError.elementType', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='elementName', full_name='rbk.protocol.msgMapError.elementName', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=214,
  serialized_end=303,
)


_MSGLICENSEERROR = _descriptor.Descriptor(
  name='msgLicenseError',
  full_name='rbk.protocol.msgLicenseError',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='licenseType', full_name='rbk.protocol.msgLicenseError.licenseType', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=305,
  serialized_end=343,
)


_MSGTASKERROR = _descriptor.Descriptor(
  name='msgTaskError',
  full_name='rbk.protocol.msgTaskError',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='task', full_name='rbk.protocol.msgTaskError.task', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=345,
  serialized_end=373,
)


_MSGERROR = _descriptor.Descriptor(
  name='msgError',
  full_name='rbk.protocol.msgError',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='deviceError', full_name='rbk.protocol.msgError.deviceError', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='configError', full_name='rbk.protocol.msgError.configError', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mapError', full_name='rbk.protocol.msgError.mapError', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='licenseError', full_name='rbk.protocol.msgError.licenseError', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='taskError', full_name='rbk.protocol.msgError.taskError', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='desc', full_name='rbk.protocol.msgError.desc', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='manual', full_name='rbk.protocol.msgError.manual', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='errorType', full_name='rbk.protocol.msgError.errorType',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=376,
  serialized_end=686,
)


_MSGSYSTEMSTATUS_ERRORSENTRY = _descriptor.Descriptor(
  name='ErrorsEntry',
  full_name='rbk.protocol.msgSystemStatus.ErrorsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='rbk.protocol.msgSystemStatus.ErrorsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='rbk.protocol.msgSystemStatus.ErrorsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=827,
  serialized_end=896,
)

_MSGSYSTEMSTATUS = _descriptor.Descriptor(
  name='msgSystemStatus',
  full_name='rbk.protocol.msgSystemStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='rbk.protocol.msgSystemStatus.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='errors', full_name='rbk.protocol.msgSystemStatus.errors', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_MSGSYSTEMSTATUS_ERRORSENTRY, ],
  enum_types=[
    _MSGSYSTEMSTATUS_SYSTEMSTATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=689,
  serialized_end=963,
)

_MSGERROR.fields_by_name['deviceError'].message_type = _MSGDEVICEERROR
_MSGERROR.fields_by_name['configError'].message_type = _MSGCONFIGERROR
_MSGERROR.fields_by_name['mapError'].message_type = _MSGMAPERROR
_MSGERROR.fields_by_name['licenseError'].message_type = _MSGLICENSEERROR
_MSGERROR.fields_by_name['taskError'].message_type = _MSGTASKERROR
_MSGERROR.oneofs_by_name['errorType'].fields.append(
  _MSGERROR.fields_by_name['deviceError'])
_MSGERROR.fields_by_name['deviceError'].containing_oneof = _MSGERROR.oneofs_by_name['errorType']
_MSGERROR.oneofs_by_name['errorType'].fields.append(
  _MSGERROR.fields_by_name['configError'])
_MSGERROR.fields_by_name['configError'].containing_oneof = _MSGERROR.oneofs_by_name['errorType']
_MSGERROR.oneofs_by_name['errorType'].fields.append(
  _MSGERROR.fields_by_name['mapError'])
_MSGERROR.fields_by_name['mapError'].containing_oneof = _MSGERROR.oneofs_by_name['errorType']
_MSGERROR.oneofs_by_name['errorType'].fields.append(
  _MSGERROR.fields_by_name['licenseError'])
_MSGERROR.fields_by_name['licenseError'].containing_oneof = _MSGERROR.oneofs_by_name['errorType']
_MSGERROR.oneofs_by_name['errorType'].fields.append(
  _MSGERROR.fields_by_name['taskError'])
_MSGERROR.fields_by_name['taskError'].containing_oneof = _MSGERROR.oneofs_by_name['errorType']
_MSGSYSTEMSTATUS_ERRORSENTRY.fields_by_name['value'].message_type = _MSGERROR
_MSGSYSTEMSTATUS_ERRORSENTRY.containing_type = _MSGSYSTEMSTATUS
_MSGSYSTEMSTATUS.fields_by_name['status'].enum_type = _MSGSYSTEMSTATUS_SYSTEMSTATUS
_MSGSYSTEMSTATUS.fields_by_name['errors'].message_type = _MSGSYSTEMSTATUS_ERRORSENTRY
_MSGSYSTEMSTATUS_SYSTEMSTATUS.containing_type = _MSGSYSTEMSTATUS
DESCRIPTOR.message_types_by_name['msgConfigError'] = _MSGCONFIGERROR
DESCRIPTOR.message_types_by_name['msgDeviceError'] = _MSGDEVICEERROR
DESCRIPTOR.message_types_by_name['msgMapError'] = _MSGMAPERROR
DESCRIPTOR.message_types_by_name['msgLicenseError'] = _MSGLICENSEERROR
DESCRIPTOR.message_types_by_name['msgTaskError'] = _MSGTASKERROR
DESCRIPTOR.message_types_by_name['msgError'] = _MSGERROR
DESCRIPTOR.message_types_by_name['msgSystemStatus'] = _MSGSYSTEMSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

msgConfigError = _reflection.GeneratedProtocolMessageType('msgConfigError', (_message.Message,), dict(
  DESCRIPTOR = _MSGCONFIGERROR,
  __module__ = 'message_error_pb2'
  # @@protoc_insertion_point(class_scope:rbk.protocol.msgConfigError)
  ))
_sym_db.RegisterMessage(msgConfigError)

msgDeviceError = _reflection.GeneratedProtocolMessageType('msgDeviceError', (_message.Message,), dict(
  DESCRIPTOR = _MSGDEVICEERROR,
  __module__ = 'message_error_pb2'
  # @@protoc_insertion_point(class_scope:rbk.protocol.msgDeviceError)
  ))
_sym_db.RegisterMessage(msgDeviceError)

msgMapError = _reflection.GeneratedProtocolMessageType('msgMapError', (_message.Message,), dict(
  DESCRIPTOR = _MSGMAPERROR,
  __module__ = 'message_error_pb2'
  # @@protoc_insertion_point(class_scope:rbk.protocol.msgMapError)
  ))
_sym_db.RegisterMessage(msgMapError)

msgLicenseError = _reflection.GeneratedProtocolMessageType('msgLicenseError', (_message.Message,), dict(
  DESCRIPTOR = _MSGLICENSEERROR,
  __module__ = 'message_error_pb2'
  # @@protoc_insertion_point(class_scope:rbk.protocol.msgLicenseError)
  ))
_sym_db.RegisterMessage(msgLicenseError)

msgTaskError = _reflection.GeneratedProtocolMessageType('msgTaskError', (_message.Message,), dict(
  DESCRIPTOR = _MSGTASKERROR,
  __module__ = 'message_error_pb2'
  # @@protoc_insertion_point(class_scope:rbk.protocol.msgTaskError)
  ))
_sym_db.RegisterMessage(msgTaskError)

msgError = _reflection.GeneratedProtocolMessageType('msgError', (_message.Message,), dict(
  DESCRIPTOR = _MSGERROR,
  __module__ = 'message_error_pb2'
  # @@protoc_insertion_point(class_scope:rbk.protocol.msgError)
  ))
_sym_db.RegisterMessage(msgError)

msgSystemStatus = _reflection.GeneratedProtocolMessageType('msgSystemStatus', (_message.Message,), dict(

  ErrorsEntry = _reflection.GeneratedProtocolMessageType('ErrorsEntry', (_message.Message,), dict(
    DESCRIPTOR = _MSGSYSTEMSTATUS_ERRORSENTRY,
    __module__ = 'message_error_pb2'
    # @@protoc_insertion_point(class_scope:rbk.protocol.msgSystemStatus.ErrorsEntry)
    ))
  ,
  DESCRIPTOR = _MSGSYSTEMSTATUS,
  __module__ = 'message_error_pb2'
  # @@protoc_insertion_point(class_scope:rbk.protocol.msgSystemStatus)
  ))
_sym_db.RegisterMessage(msgSystemStatus)
_sym_db.RegisterMessage(msgSystemStatus.ErrorsEntry)


_MSGSYSTEMSTATUS_ERRORSENTRY._options = None
# @@protoc_insertion_point(module_scope)
