# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_codescanner.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import message_header_pb2 as message__header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='message_codescanner.proto',
  package='rbk.protocol',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x19message_codescanner.proto\x12\x0crbk.protocol\x1a\x14message_header.proto\"\xac\x01\n\x12msgCodeScannerInfo\x12\x17\n\x0f\x63odeScannerName\x18\x01 \x01(\t\x12\t\n\x01x\x18\x02 \x01(\x01\x12\t\n\x01y\x18\x03 \x01(\x01\x12\t\n\x01z\x18\x04 \x01(\x01\x12\x0b\n\x03yaw\x18\x05 \x01(\x01\x12\r\n\x05pitch\x18\x06 \x01(\x01\x12\x0c\n\x04roll\x18\x07 \x01(\x01\x12\x0c\n\x04\x66unc\x18\x08 \x01(\t\x12\x12\n\ncoordinate\x18\t \x01(\t\x12\x10\n\x08isUpside\x18\n \x01(\x08\"\x95\x02\n\x11msgCodeScannerDMT\x12\x10\n\x08tagDiffX\x18\x01 \x01(\x01\x12\x10\n\x08tagDiffY\x18\x02 \x01(\x01\x12\x14\n\x0ctagDiffAngle\x18\x03 \x01(\x01\x12\x10\n\x08tagValue\x18\x04 \x01(\r\x12\x13\n\x0bwarningCode\x18\x05 \x01(\r\x12\x15\n\risDMTDetected\x18\x06 \x01(\x08\x12\x11\n\terrorCode\x18\x07 \x01(\r\x12\'\n\x06header\x18\x08 \x01(\x0b\x32\x17.rbk.protocol.msgHeader\x12\x39\n\x0f\x63odeScannerInfo\x18\t \x01(\x0b\x32 .rbk.protocol.msgCodeScannerInfo\x12\x11\n\tisBarCode\x18\n \x01(\x08\"G\n\x0emsgCodeScanner\x12\x35\n\x0c\x63odeScanners\x18\x01 \x03(\x0b\x32\x1f.rbk.protocol.msgCodeScannerDMTb\x06proto3')
  ,
  dependencies=[message__header__pb2.DESCRIPTOR,])




_MSGCODESCANNERINFO = _descriptor.Descriptor(
  name='msgCodeScannerInfo',
  full_name='rbk.protocol.msgCodeScannerInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='codeScannerName', full_name='rbk.protocol.msgCodeScannerInfo.codeScannerName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x', full_name='rbk.protocol.msgCodeScannerInfo.x', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='rbk.protocol.msgCodeScannerInfo.y', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='rbk.protocol.msgCodeScannerInfo.z', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='yaw', full_name='rbk.protocol.msgCodeScannerInfo.yaw', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pitch', full_name='rbk.protocol.msgCodeScannerInfo.pitch', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='roll', full_name='rbk.protocol.msgCodeScannerInfo.roll', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='func', full_name='rbk.protocol.msgCodeScannerInfo.func', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='coordinate', full_name='rbk.protocol.msgCodeScannerInfo.coordinate', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isUpside', full_name='rbk.protocol.msgCodeScannerInfo.isUpside', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=238,
)


_MSGCODESCANNERDMT = _descriptor.Descriptor(
  name='msgCodeScannerDMT',
  full_name='rbk.protocol.msgCodeScannerDMT',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tagDiffX', full_name='rbk.protocol.msgCodeScannerDMT.tagDiffX', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tagDiffY', full_name='rbk.protocol.msgCodeScannerDMT.tagDiffY', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tagDiffAngle', full_name='rbk.protocol.msgCodeScannerDMT.tagDiffAngle', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tagValue', full_name='rbk.protocol.msgCodeScannerDMT.tagValue', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='warningCode', full_name='rbk.protocol.msgCodeScannerDMT.warningCode', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isDMTDetected', full_name='rbk.protocol.msgCodeScannerDMT.isDMTDetected', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='errorCode', full_name='rbk.protocol.msgCodeScannerDMT.errorCode', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='header', full_name='rbk.protocol.msgCodeScannerDMT.header', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='codeScannerInfo', full_name='rbk.protocol.msgCodeScannerDMT.codeScannerInfo', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isBarCode', full_name='rbk.protocol.msgCodeScannerDMT.isBarCode', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=241,
  serialized_end=518,
)


_MSGCODESCANNER = _descriptor.Descriptor(
  name='msgCodeScanner',
  full_name='rbk.protocol.msgCodeScanner',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='codeScanners', full_name='rbk.protocol.msgCodeScanner.codeScanners', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=520,
  serialized_end=591,
)

_MSGCODESCANNERDMT.fields_by_name['header'].message_type = message__header__pb2._MSGHEADER
_MSGCODESCANNERDMT.fields_by_name['codeScannerInfo'].message_type = _MSGCODESCANNERINFO
_MSGCODESCANNER.fields_by_name['codeScanners'].message_type = _MSGCODESCANNERDMT
DESCRIPTOR.message_types_by_name['msgCodeScannerInfo'] = _MSGCODESCANNERINFO
DESCRIPTOR.message_types_by_name['msgCodeScannerDMT'] = _MSGCODESCANNERDMT
DESCRIPTOR.message_types_by_name['msgCodeScanner'] = _MSGCODESCANNER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

msgCodeScannerInfo = _reflection.GeneratedProtocolMessageType('msgCodeScannerInfo', (_message.Message,), dict(
  DESCRIPTOR = _MSGCODESCANNERINFO,
  __module__ = 'message_codescanner_pb2'
  # @@protoc_insertion_point(class_scope:rbk.protocol.msgCodeScannerInfo)
  ))
_sym_db.RegisterMessage(msgCodeScannerInfo)

msgCodeScannerDMT = _reflection.GeneratedProtocolMessageType('msgCodeScannerDMT', (_message.Message,), dict(
  DESCRIPTOR = _MSGCODESCANNERDMT,
  __module__ = 'message_codescanner_pb2'
  # @@protoc_insertion_point(class_scope:rbk.protocol.msgCodeScannerDMT)
  ))
_sym_db.RegisterMessage(msgCodeScannerDMT)

msgCodeScanner = _reflection.GeneratedProtocolMessageType('msgCodeScanner', (_message.Message,), dict(
  DESCRIPTOR = _MSGCODESCANNER,
  __module__ = 'message_codescanner_pb2'
  # @@protoc_insertion_point(class_scope:rbk.protocol.msgCodeScanner)
  ))
_sym_db.RegisterMessage(msgCodeScanner)


# @@protoc_insertion_point(module_scope)
