# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_battery.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message_battery.proto',
  package='rbk.protocol',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x15message_battery.proto\x12\x0crbk.protocol\"\xcd\x02\n\nmsgBattery\x12\x12\n\npercentage\x18\x01 \x01(\x01\x12\x15\n\rchargeCurrent\x18\x02 \x01(\x01\x12\x15\n\rchargeVoltage\x18\x03 \x01(\x01\x12\x12\n\nisCharging\x18\x04 \x01(\x08\x12\x13\n\x0btemperature\x18\x05 \x01(\x01\x12\r\n\x05\x63ycle\x18\x06 \x01(\x05\x12\x18\n\x10maxChargeCurrent\x18\x07 \x01(\x01\x12\x18\n\x10maxChargeVoltage\x18\x08 \x01(\x01\x12\r\n\x05\x65xtra\x18\t \x01(\t\x12\x1b\n\x13isManuallyConnected\x18\n \x01(\x08\x12\x11\n\terrorCode\x18\x0b \x01(\r\x12\x0b\n\x03SOH\x18\x0c \x01(\x05\x12\x16\n\x0eneedFullCharge\x18\r \x01(\x08\x12\x1b\n\x13lastFullChargeStamp\x18\x0e \x01(\x04\x12\x10\n\x08userData\x18\x1e \x01(\x0c\x62\x06proto3')
)




_MSGBATTERY = _descriptor.Descriptor(
  name='msgBattery',
  full_name='rbk.protocol.msgBattery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='percentage', full_name='rbk.protocol.msgBattery.percentage', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='chargeCurrent', full_name='rbk.protocol.msgBattery.chargeCurrent', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='chargeVoltage', full_name='rbk.protocol.msgBattery.chargeVoltage', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isCharging', full_name='rbk.protocol.msgBattery.isCharging', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='temperature', full_name='rbk.protocol.msgBattery.temperature', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cycle', full_name='rbk.protocol.msgBattery.cycle', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='maxChargeCurrent', full_name='rbk.protocol.msgBattery.maxChargeCurrent', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='maxChargeVoltage', full_name='rbk.protocol.msgBattery.maxChargeVoltage', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='extra', full_name='rbk.protocol.msgBattery.extra', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isManuallyConnected', full_name='rbk.protocol.msgBattery.isManuallyConnected', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='errorCode', full_name='rbk.protocol.msgBattery.errorCode', index=10,
      number=11, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='SOH', full_name='rbk.protocol.msgBattery.SOH', index=11,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='needFullCharge', full_name='rbk.protocol.msgBattery.needFullCharge', index=12,
      number=13, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lastFullChargeStamp', full_name='rbk.protocol.msgBattery.lastFullChargeStamp', index=13,
      number=14, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='userData', full_name='rbk.protocol.msgBattery.userData', index=14,
      number=30, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=373,
)

DESCRIPTOR.message_types_by_name['msgBattery'] = _MSGBATTERY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

msgBattery = _reflection.GeneratedProtocolMessageType('msgBattery', (_message.Message,), dict(
  DESCRIPTOR = _MSGBATTERY,
  __module__ = 'message_battery_pb2'
  # @@protoc_insertion_point(class_scope:rbk.protocol.msgBattery)
  ))
_sym_db.RegisterMessage(msgBattery)


# @@protoc_insertion_point(module_scope)
