# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_dmx512.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message_dmx512.proto',
  package='rbk.protocol',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x14message_dmx512.proto\x12\x0crbk.protocol\"\x90\x01\n\tmsgDmx512\x12\x0c\n\x04type\x18\x01 \x01(\r\x12\x0f\n\x07\x62\x61ttery\x18\x02 \x01(\r\x12\x10\n\x08\x63olorRed\x18\x03 \x01(\r\x12\x12\n\ncolorGreen\x18\x04 \x01(\r\x12\x11\n\tcolorBlue\x18\x05 \x01(\r\x12\x12\n\ncolorWhite\x18\x06 \x01(\r\x12\x17\n\x0fturnLeftOrRight\x18\x07 \x01(\rb\x06proto3')
)




_MSGDMX512 = _descriptor.Descriptor(
  name='msgDmx512',
  full_name='rbk.protocol.msgDmx512',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='rbk.protocol.msgDmx512.type', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='battery', full_name='rbk.protocol.msgDmx512.battery', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='colorRed', full_name='rbk.protocol.msgDmx512.colorRed', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='colorGreen', full_name='rbk.protocol.msgDmx512.colorGreen', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='colorBlue', full_name='rbk.protocol.msgDmx512.colorBlue', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='colorWhite', full_name='rbk.protocol.msgDmx512.colorWhite', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='turnLeftOrRight', full_name='rbk.protocol.msgDmx512.turnLeftOrRight', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=183,
)

DESCRIPTOR.message_types_by_name['msgDmx512'] = _MSGDMX512
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

msgDmx512 = _reflection.GeneratedProtocolMessageType('msgDmx512', (_message.Message,), dict(
  DESCRIPTOR = _MSGDMX512,
  __module__ = 'message_dmx512_pb2'
  # @@protoc_insertion_point(class_scope:rbk.protocol.msgDmx512)
  ))
_sym_db.RegisterMessage(msgDmx512)


# @@protoc_insertion_point(module_scope)
