# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_rfid.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import message_header_pb2 as message__header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='message_rfid.proto',
  package='rbk.protocol',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12message_rfid.proto\x12\x0crbk.protocol\x1a\x14message_header.proto\"p\n\x0bmsgRFIDNode\x12\n\n\x02id\x18\x01 \x01(\r\x12\r\n\x05\x63ount\x18\x02 \x01(\r\x12\'\n\x06header\x18\x03 \x01(\x0b\x32\x17.rbk.protocol.msgHeader\x12\x10\n\x08strength\x18\x04 \x01(\r\x12\x0b\n\x03key\x18\x05 \x01(\t\"7\n\x07msgRFID\x12,\n\trfidNodes\x18\x01 \x03(\x0b\x32\x19.rbk.protocol.msgRFIDNodeb\x06proto3')
  ,
  dependencies=[message__header__pb2.DESCRIPTOR,])




_MSGRFIDNODE = _descriptor.Descriptor(
  name='msgRFIDNode',
  full_name='rbk.protocol.msgRFIDNode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='rbk.protocol.msgRFIDNode.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='count', full_name='rbk.protocol.msgRFIDNode.count', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='header', full_name='rbk.protocol.msgRFIDNode.header', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='strength', full_name='rbk.protocol.msgRFIDNode.strength', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key', full_name='rbk.protocol.msgRFIDNode.key', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=170,
)


_MSGRFID = _descriptor.Descriptor(
  name='msgRFID',
  full_name='rbk.protocol.msgRFID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rfidNodes', full_name='rbk.protocol.msgRFID.rfidNodes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=172,
  serialized_end=227,
)

_MSGRFIDNODE.fields_by_name['header'].message_type = message__header__pb2._MSGHEADER
_MSGRFID.fields_by_name['rfidNodes'].message_type = _MSGRFIDNODE
DESCRIPTOR.message_types_by_name['msgRFIDNode'] = _MSGRFIDNODE
DESCRIPTOR.message_types_by_name['msgRFID'] = _MSGRFID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

msgRFIDNode = _reflection.GeneratedProtocolMessageType('msgRFIDNode', (_message.Message,), dict(
  DESCRIPTOR = _MSGRFIDNODE,
  __module__ = 'message_rfid_pb2'
  # @@protoc_insertion_point(class_scope:rbk.protocol.msgRFIDNode)
  ))
_sym_db.RegisterMessage(msgRFIDNode)

msgRFID = _reflection.GeneratedProtocolMessageType('msgRFID', (_message.Message,), dict(
  DESCRIPTOR = _MSGRFID,
  __module__ = 'message_rfid_pb2'
  # @@protoc_insertion_point(class_scope:rbk.protocol.msgRFID)
  ))
_sym_db.RegisterMessage(msgRFID)


# @@protoc_insertion_point(module_scope)
