import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode("latin1"))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

_sym_db = _symbol_database.Default()
from . import messageV4_header_pb2 as messageV4__header__pb2

DESCRIPTOR = _descriptor.FileDescriptor(
    name="messageV4_ethercat_extendinfo.proto",
    package="rbk4.protocol",
    syntax="proto3",
    serialized_options=None,
    serialized_pb=_b(
        '\n#messageV4_ethercat_extendinfo.proto\x12\rrbk4.protocol\x1a\x16messageV4_header.proto"\x80\x01\n\x1cMessageV4_EtherCATExtendInfo\x12/\n\x06header\x18\x01 \x01(\x0b2\x1f.rbk4.protocol.MessageV4_Header\x12\x0e\n\x06length\x18\x02 \x01(\r\x12\x0c\n\x04data\x18\x03 \x01(\x0c\x12\x11\n\tdi_status\x18\x04 \x01(\r"¡\x01\n#MessageV4_EtherCATExtendBrainCoInfo\x12/\n\x06header\x18\x01 \x01(\x0b2\x1f.rbk4.protocol.MessageV4_Header\x12\x10\n\x08pos_data\x18\x02 \x03(\r\x12\x10\n\x08vel_data\x18\x03 \x03(\x05\x12\x10\n\x08cur_data\x18\x04 \x03(\x05\x12\x13\n\x0bstatus_data\x18\x05 \x03(\rb\x06proto3'
    ),
    dependencies=[messageV4__header__pb2.DESCRIPTOR],
)
_MESSAGEV4_ETHERCATEXTENDINFO = _descriptor.Descriptor(
    name="MessageV4_EtherCATExtendInfo",
    full_name="rbk4.protocol.MessageV4_EtherCATExtendInfo",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="header",
            full_name="rbk4.protocol.MessageV4_EtherCATExtendInfo.header",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="length",
            full_name="rbk4.protocol.MessageV4_EtherCATExtendInfo.length",
            index=1,
            number=2,
            type=13,
            cpp_type=3,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="data",
            full_name="rbk4.protocol.MessageV4_EtherCATExtendInfo.data",
            index=2,
            number=3,
            type=12,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b(""),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="di_status",
            full_name="rbk4.protocol.MessageV4_EtherCATExtendInfo.di_status",
            index=3,
            number=4,
            type=13,
            cpp_type=3,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=79,
    serialized_end=207,
)
_MESSAGEV4_ETHERCATEXTENDBRAINCOINFO = _descriptor.Descriptor(
    name="MessageV4_EtherCATExtendBrainCoInfo",
    full_name="rbk4.protocol.MessageV4_EtherCATExtendBrainCoInfo",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="header",
            full_name="rbk4.protocol.MessageV4_EtherCATExtendBrainCoInfo.header",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="pos_data",
            full_name="rbk4.protocol.MessageV4_EtherCATExtendBrainCoInfo.pos_data",
            index=1,
            number=2,
            type=13,
            cpp_type=3,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="vel_data",
            full_name="rbk4.protocol.MessageV4_EtherCATExtendBrainCoInfo.vel_data",
            index=2,
            number=3,
            type=5,
            cpp_type=1,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="cur_data",
            full_name="rbk4.protocol.MessageV4_EtherCATExtendBrainCoInfo.cur_data",
            index=3,
            number=4,
            type=5,
            cpp_type=1,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="status_data",
            full_name="rbk4.protocol.MessageV4_EtherCATExtendBrainCoInfo.status_data",
            index=4,
            number=5,
            type=13,
            cpp_type=3,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=210,
    serialized_end=371,
)
_MESSAGEV4_ETHERCATEXTENDINFO.fields_by_name["header"].message_type = (
    messageV4__header__pb2._MESSAGEV4_HEADER
)
_MESSAGEV4_ETHERCATEXTENDBRAINCOINFO.fields_by_name["header"].message_type = (
    messageV4__header__pb2._MESSAGEV4_HEADER
)
DESCRIPTOR.message_types_by_name["MessageV4_EtherCATExtendInfo"] = (
    _MESSAGEV4_ETHERCATEXTENDINFO
)
DESCRIPTOR.message_types_by_name["MessageV4_EtherCATExtendBrainCoInfo"] = (
    _MESSAGEV4_ETHERCATEXTENDBRAINCOINFO
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)
MessageV4_EtherCATExtendInfo = _reflection.GeneratedProtocolMessageType(
    "MessageV4_EtherCATExtendInfo",
    (_message.Message,),
    dict(
        DESCRIPTOR=_MESSAGEV4_ETHERCATEXTENDINFO,
        __module__="messageV4_ethercat_extendinfo_pb2",
    ),
)
_sym_db.RegisterMessage(MessageV4_EtherCATExtendInfo)
MessageV4_EtherCATExtendBrainCoInfo = _reflection.GeneratedProtocolMessageType(
    "MessageV4_EtherCATExtendBrainCoInfo",
    (_message.Message,),
    dict(
        DESCRIPTOR=_MESSAGEV4_ETHERCATEXTENDBRAINCOINFO,
        __module__="messageV4_ethercat_extendinfo_pb2",
    ),
)
_sym_db.RegisterMessage(MessageV4_EtherCATExtendBrainCoInfo)
