syntax = "proto3";
package rbk.protocol;
import "message_header.proto";

message Message_Localization {
  enum UpdateReason {
    None = 0;
    OdoUpdate = 1;
    LaserCorrec = 2;
    LaserThenOdo = 3;
    PGVCORRECT = 4;
  }
  Message_Header header = 1;
  double x = 2;
  double y = 3;
  double angle = 4;
  double confidence = 5;
  repeated double correction_errs = 6;
  repeated double reliabilities = 7;
  bool in_forbidden_area = 8;
  UpdateReason update_reason = 9;
  enum LocState {
    Normal = 0;
    Skidding = 1;
    LowConfidence = 2;
  }
  LocState loc_state = 10;
  double similarity = 11;
  enum LocMethod
  {
    PF_LASER_2D = 0;
    SLAM_2D = 1;
    PGV = 2;
    REFLECTOR = 3;
    LASER_3D = 4;
    BAR_CODE = 5;
  }
  LocMethod loc_method = 12;
  // 增加车体相对与水平面的roll和pitch
  // 单位 deg
  double roll = 13;
  // 单位 deg
  double pitch = 14;
}

message Message_LocFinished{
  bool value = 1;
}


message Message_3DPose{
  Message_Header header = 1;

  double x = 2;
  double y = 3;
  double z = 4;

  double q_w = 5;
  double q_x = 6;
  double q_y = 7;
  double q_z = 8;

  string extra_data = 9;
}
// 红外相机定位消息发布
message Message_IRCAMPose{
  Message_3DPose pose = 1;
}


// 2D相机参数信息
message Message_2D_CamInfo
{
  Message_Header header = 1;
  string camera_name = 2;

  double  m_infrared = 3;
  double  m_seertag_size = 4;
  double  m_seertag_family_id = 5;
  string  model_type = 6; //PINHOLE
  string  distortion_modle = 7;

  bool is_intrinsics_caib = 8;
  bool is_extrinsics_caib = 9;
  // 相机外参
  double x = 10;
  double y = 11;
  double z = 12;

  double roll = 13;
  double pitch = 14;
  double yaw = 15;

  // 相机内参
  double m_fx_ = 16;
  double m_fy_ = 17;
  double m_cx_ = 18;
  double m_cy_ = 19;
  double m_k1_ = 20;
  double m_k2_ = 21;
  double m_k3_ = 22;
  double m_k4_ = 23;
  double m_k5_ = 24;
  double m_k6_ = 25;
  double m_p1_ = 26;
  double m_p2_ = 27;
}
